### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by gatastuff** [G-D-B-9-9/X-Twitter-LSposed-MOD-#1]
Hello! This project  is awesome. Could you do the same with instagram and tik tok ?

**Comment by G-D-B-9-9** [comment]
Use revanced

**Comment by gatastuff** [comment]
Could you give me some link?

**Comment by gatastuff** [comment]
Please these apks are spectacular and consume very little battery. I know I'm bothering you but could you do the same modified apk for instagram and tik tok as well?

**Comment by G-D-B-9-9** [comment]
Search github: revanced manager
Then download microg
Install them

Then download Instagram and tiktok from apkmirror and patch with revanced manager

Search Google: revanced manager for dummies
(In Reddit)

:) it details the installation specifically
